all:
	javac Main.java Menu.java Actions/ActionInventaireEnPlein.java Actions/ActionInventaireRelascopiqueRegulier.java Actions/ActionInventaireRelascopiqueIrregulier.java
	java Main

run:
	java Main

clean clear:
	rm *.class
	rm Actions/*.class
